### PR TITLE
Cannot do 36B. Rest OK.

### PR DESCRIPTION
**Pull request by magnum7701**
36B not done

### CODE REVIEW

**Comment by lord-cyclone100** [comment]
32B) 1 is an ugly number but the code shows 1 is not ugly
38A) Pls optimize the code. The ladder looks bad.
@magnum7701 pls make these changes then i shall merge

**Comment by magnum7701** [comment]
@lord-cyclone100 fixed

**Comment by lord-cyclone100** [comment]
@magnum7701 pls attach the graph of question 38A with the file name as 38A-graph.png
Also pls git pull as i have edited some of my code

**Comment by magnum7701** [comment]
@lord-cyclone100 graph added

**Comment by lord-cyclone100** [comment]
Thanks for you contribution @magnum7701

**Pull request merged**
